name: Package and Push Helm Chart

on:
  push:
    branches:
      - ft-setup-github-actions  # Change this to your target branch

jobs:
  package_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.6.3'  # Change to the desired Helm version

    - name: Package Helm Chart
      run: |
        helm package ./projects3
      working-directory: ./projects3

    - name: Configure S3 Plugin
      run: |
        helm plugin install https://github.com/hypnoglow/helm-s3.git
      #  helm repo add s3-repo s3://your-s3-bucket/path/to/charts
      working-directory: .

    #- name: Push Helm Chart to S3
    #  run: |
    #    helm s3 push ./your-chart-*.tgz s3-repo
    #   working-directory: ./path/to/output
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
